export const AUTH = "AUTH";
export const USER_DATA = "USER_DATA";
export const USER_STATS = "USER_STATS";
export const USER_INVENTORY_ADD = "USER_INVENTORY_ADD";
export const USER_INVENTORY_REMOVE = "USER_INVENTORY_REMOVE";
export const USER_INVENTORY_DELETE = "USER_INVENTORY_DELETE";
export const USER_INVENTORY_CHECK = "USER_INVENTORY_CHECK";
export const USER_INVENTORY_UNCHECK = "USER_INVENTORY_UNCHECK";

export const SWITCHER_RIGHTS = "SWITCHER_RIGHTS";

export const AIRDROP_TIMER_SECONDS = "AIRDROP_TIMER_SECONDS";
export const AIRDROP_MEMBERS_ADD = "AIRDROP_MEMBERS_ADD";
export const AIRDROP_TRAJECTORY_PLANE = "AIRDROP_TRAJECTORY_PLANE";
export const AIRDROP_LENGTH_PLANE = "AIRDROP_LENGTH_PLANE";
export const AIRDROP_STEP = "AIRDROP_STEP";
export const AIRDROP_STEP_RIGHTS = "AIRDROP_STEP_RIGHTS";
export const AIRDROP_DROP_SET_COODS = "AIRDROP_DROP_SET_COODS";
export const AIRDROP_DROP_IS_DROP_DOWN = "AIRDROP_DROP_IS_DROP_DOWN";
export const AIRDROP_COUNT_SLEEPERS = "AIRDROP_COUNT_SLEEPERS";

export const SHOP_LIST = "SHOP_LIST";
export const SHOP_LIST_ADD = "SHOP_LIST_ADD";
export const SHOP_LIST_REMOVE = "SHOP_LIST_REMOVE";

export const PROCESSOR_LIST_ADD = "PROCESSOR_LIST_ADD";
export const PROCESSOR_LIST_REMOVE = "PROCESSOR_LIST_REMOVE";
export const PROCESSOR_LIST_DELETE = "PROCESSOR_LIST_DELETE";

export const STORAGE_WITHDRAW_TOGGLE = "STORAGE_WITHDRAW_TOGGLE";
export const STORAGE_WITHDRAW_DELETE = "STORAGE_WITHDRAW_DELETE";